name 'sandy-storage'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sandy-storage'
long_description 'Installs/Configures sandy-storage'
version '0.4.1'

depends 'gina-gluster'
depends 'yum-epel'
depends 'lvm'
depends 'xfs'
